apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-sample-ingress
spec:
  ingressClassName: ingress-internal
  rules:
  - host: cloud-sample.cepg-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: cloud-sample
            port:
              number: 8080
        pathType: Prefix